// actionTypes.js
export const FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SORT_COUNTRIES = "SORT_COUNTRIES";

export const FETCH_ACT = "FETCH_ACT";
